site_name: Personal Development Environment
theme: 
  name: material
docs_dir: environment

nav:
  - Home: index.md
  - Brewfile: brewfile.md

plugins:
  - macros

theme:
  features:
    - navigation.tabs